#!/usr/bin/env python2
# written by Moses Arocha
# Written with the help of TJ O'Connor in his book "Violent Python"

from _winreg import *

def BinaryToMac(val):
	addr = '';
	for ch in val:
	   addr += '%02x '% ord(ch)
	addr = addr.strip(' ').replace(' ', ':')[0:17]
	return addr

def PrintNetworks():
	net = "SOFTWARE\Microsoft\Windows NT\CurrentVerison\NetworkList\Signatures\Unmanaged"
	key = OpenKey(HKEY_LOCAL_MACHINE, net)
	print '\n\t[*] Networks You Have Joined.'
	for i in range(100):
		guid = EnumKey(key, i)
		netKey = OpenKey(key, str(guid))
		(n, addr, t) = EnumValue(netKey, 5)
		(n, name, t) = EnumValue(netKey, 4)
		MACAddr = BinaryToMac(addr)
		netName = str(name)
		print '[+] ' + netName + ' ' + MACAddr
		CloseKey(netKey)

def main():
	PrintNetworks()
	

if __name__ == "__main__":
	main()
