#!/usr/bin/env python2
# written by Moses Arocha
# Written with the help of TJ O'Connor in his book "Violent Python"

import urllib2
import optparse
from urlparse import urlsplit
from os.path import basename
from bs4 import BeautifulSoup
from PIL import Image
from PIL.ExifTags import TAGS

def URLImages(url):
	print '\n\n[+] Searching For Images On : ' + url +'\n'
	urlContent = urllib2.urlopen(url).read()
	soup = BeautifulSoup(urlContent, "lxml")
	ImageTags = soup.findAll('img')
	return ImageTags

def downloadImage(ImageTag):
	try:
		print '[Attempt] Scanning Image ...'
		ImageSource = ImageTag['src']
		ImageContent = urllib2.urlopen(ImageSource).read()
		ImageName = basename(urlsplit(ImageSource)[2])
		ImageFile = open(ImageName, 'wb')
		ImageFile.write(ImageContent)
		ImageFile.close()
		return ImageName
	except:
		return ''

def checkExifData(ImageName):
	try:
		exifData = {}
		ImageFile = Image.open(ImageName)
		Data = ImageFile._getexif()
		if Data:
			for (tag,value) in Data.items():
				decoded = TAGS.get(tag, tag)
				exifData[decoded] = value
			exifGPS = exifData['GPSInfo']
			if exifGPS:
				print '\t[Success] ' + ImageName + ' This Image Contains GPS Data'
	except:
		pass

def main():
	parser = optparse.OptionParser('usage%prog -U <Target URLl>')
	parser.add_option('-U', '--URL', dest='url', type='string', help='Specify URL ADDRESS')
	(options, args) = parser.parse_args()
	url = options.url
	if url == None:
		print parser.usage
		exit(0)
	else:
		ImageTags = URLImages(url)
		for ImageTag in ImageTags:
			ImageName = downloadImage(ImageTag)
			checkExifData(ImageName)

if __name__ == '__main__':
	main()
